#!/bin/bash
## Generate Public/Private Key Pairs for Keyless Login to Remote Host

client=$(hostname)  # Origin 
user=$(whoami)      # User @ Origin

host=$(hostname)        # Destination
user_alias=$(whoami)    # User Name @ Destination

ssh_home="${HOME}/.ssh"              # Stash ssh deets here
sshagentfile="${HOME}/.ssh_agent"    # Parameters for ssh-agent

keytype='dsa'
x11=''

proceed=''
quiet=''
resetkeys=''
bits=''

exec_all='true'
cpkeys=''
genkeys=''
addagent=''

# Define Function
## Print Usage Information
function show_help(){
cat <<EOF

Usage ${0##*/} [-h|--help] [-host ADDRESS] [-uname USERNAME] [-sshagent FILE][-sshdir PATH] [-prvkey FILE]
                    [--x11] [--reset] [--2waytunnel]

This program checks for existence of private/public keypairs for passwordless ssh logins between remote and local host.

    REQUIRED ARGUMENTS  
    
        -host       address of remote server to set up logins keys
        -uname      username credential for remote server

    SSH OPTIONS

        -sshagent   file for ssh-agent 
        -keytype    rsa | dsa
        -bits       number of bits to encode key (rsa - 2048, dsa - 1024)
        -sshdir     path to .ssh directory (keys stored here)
        -prvkey     name of private key
        -pubkey     name of public key
        --x11       permit X11 forwarding 

    OTHER FLAGS

        --status        print parameters for ssh setup and exit (use this to double check args before executing)
        --quiet         run as quietly as possible (no status print)
        --reset         CAUTION :: deletes priv/pub keys, ssh-agent files, ssh config and .bash_logout
        --keychain      download and use keychain instead of ssh-agent (brew | git for OSX/Linux)     

        The following flags can be used in combination with each other to run individual steps ::
        --keygen        this flag used alone will just generate keys (no cp keys or adding agents)
        --cpkeys        this flag used alone will just copy keys (no keygen or adding agents)
        --addagent      this flag used alone will just add an ssh-agent (no keygen or cpkeys)


EOF
}
# Parse Options 
## Shift through standard input and assign to variables using option flags
while :; do
    case ${1} in
        -h|--help)
        show_help
        exit
        ;;
        -rsa)
            keytype='rsa'
        ;;
        -dsa)
            keytype='dsa'
        ;;        
        --x11)
            x11='-O permit-x11-forwarding'
        ;;
        --quiet)
            quiet='quiet'
        ;;
        --status)
            proceed='N'
        ;;
        --keychain)
            keychain='on'        
        ;;        
        --reset)
            resetkeys='true'
        ;;
        --cpkeys)
            cpkeys='true'
            exec_all=''
        ;;
        --genkeys)
            genkeys='true'
            execall=''
        ;;
        --addagent)
            addagent='true'
            execall=''
        ;;
        -host)
            if [ -n "${2}" ]; then
                host=${2}
                shift
            else                                                                                                                                                                                                                 
                echo "ERROR: -host requires a non-empty option argument.\n" >&2
                exit
            fi
            ;;
        -uname)
            if [ -n "${2}" ]; then
                user_alias=${2}
                shift
            else
                echo "ERROR: -uname requires a non-empty option argument.\n" >&2
                exit
            fi
            ;;
        -sshagent)
            if [ -n "${2}" ]; then
                sshagentfile=${2}
                shift
            else
                echo "ERROR: -sshagent requires a non-empty option argument.\n" >&2
                exit
            fi
            ;;
        -sshdir)
            if [ -n "${2}" ]; then
                ssh_home=${2}
                shift
            else
                echo "ERROR: -sshdir requires a non-empty option argument.\n" >&2
                exit
            fi
            ;;
        -keytype)
            if [ -n "${2}" ]; then
                keytype=${2}
                shift
            else
                echo "ERROR -keytype requires a non-empty option argument" >&2
                exit
            fi
            ;;
        -bits)
            if [ -n "${2}" ]; then
                bits='-b '$2
                shift
            else
                echo "ERROR -bits requires a non-empty option argument" >&2
                exit
            fi
            ;;                                   
        -prvkey)
            if [ -n "${2}" ]; then
                privkey=${2}
                shift
            else
                echo "ERROR: -prvkey requires a non-empty option argument.\n" >&2
                exit
            fi
            ;;
        -pubkey)
            if [ -n "${2}" ]; then
                pubkey=${2}
                shift
            else
                echo "ERROR -pubkey requires a non-empty option argument" >&2
                exit
            fi
            ;;
        -?*)
            printf '\n ‼️ Warning: Unknown option: %s\n' "${1}" >&2
            exit
            ;;
        *)
            break
    esac
    shift
done
# ----------------------------------------------------------------
#                  Build Private and Public Key Names
[ -z ${privkey} ] && privkey='id_'${keytype}
[ -z ${pubkey} ] && pubkey='id_'${keytype}'.pub'
#                 Assign Option String for SSH-KEYGEN
opts="-t ${keytype} ${bits} ${x11} -f ${ssh_home}/${privkey}"
# ----------------------------------------------------------------
# Define Function
## This function displays options to user_alias and asks for verification
function confirm_input(){
local confirm_user_input=$(cat <<-EOF
    \n
    Setting up Keyless SSH Tunnel :: ${user}@${client} 📡  ⇢  🔑  ⇢ ${user_alias}@${host}
    \n
    \n
    \t    🖥  HOST\t\t\t          ::      ${host}\n
    \t    👤  USER ALIAS\t\t      ::      ${user_alias}\n\n
    \t    📁  SSHDIR\t\t          ::      ${ssh_home}\n
    \t    📝  SSHAGENTFILE\t\t    ::      ${sshagentfile}\n
    \t    🔐  KEYTYPE\t\t         ::      ${keytype}\n\n
    \t    🔑  PRIVATEKEY\t\t      ::      ${privkey}\n
    \t    🗝  PUBLICKEY\t\t       ::      ${pubkey}\n\n    
    \t    ⚙   KEYGEN OPTIONS\t    ::      ${opts}
EOF
    )   
# Check if user_alias just wants to see status
[ ! ${proceed} ] || [ ! ${quiet} ] && echo -e ${confirm_user_input}
[ ! ${quiet} ] && [ -z ${proceed} ] && read -p "Setup New Handshake? [Y/N]  :: " proceed
echo -e "\n"
[ "${proceed}" = "N" ] || [ "${proceed}" = "n" ] && exit
}
# Define Function
## This function checks for existence of hidden ssh directory in user_alias home and generates a
## public/private key pair and adds the public key to the authorized keys file.
function stdssh_genaddkeys(){
    # Check if ssh home dir exists
	[ ! -d ${ssh_home} ] && mkdir -p ${ssh_home}
    # Generate keys
    ssh-keygen ${opts}
    # Create authorized keys file
    [ ! -e ${ssh_home}/authorized_keys ] && touch ${ssh_home}/authorized_keys
    echo -e "\n ** Adding public key to authorized keys\n"
	cat ${ssh_home}/${pubkey} >> ${ssh_home}/authorized_keys
}
# Define Function
## Check permissions
function stdssh_perms(){
    echo -e "\n ** Setting Permissions To Private Key and Authorized Keys File to 600\n"
    chmod 600 ${ssh_home}/authorized_keys
    chmod 600 ${ssh_home}/${privkey}
}
# Define Function
## This function takes a remote host, username, and path to a private key and copies it
## to the home directory on the remote host. 
function stdssh_cpkey(){
	local host=${1}
	local user=${2}
	local key=${3}
	local rseed=${RANDOM}
    echo -e "\n  🖥   📡  🤙  🎛  🤘  Securely Transmitting Secret Handshake \n"
    echo -e "Appending $client pubkey to authorized keys on $host"
    cat ${ssh_home}'/'${key} | ssh ${user}'@'${host} '[ ! -d ~/.ssh ] && mkdir ~/.ssh; cat >> ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys'
    #echo -e "Sending $client private key to $host"
	#scp ${ssh_home}'/'${privkey} ${username}'@'${host}:'/tmp/'${privkey}'.transfer.'${rseed}
    #echo -e "Setting up $client private key on $host"
	#ssh ${username}'@'${host} "[ ! -e  ~/.keys ] && mkdir ~/.keys; mv /tmp/${privkey}.transfer.${rseed} ~/.keys/; chmod 400 ~/.keys/${privkey}.transfer.${rseed}"
}
# Define Function
## Use keychain utility to add keys to ssh-agent (Very convenient)
function stdssh_addkeychain(){
    if [ -z $(which keychain) ]; then
        if [ $(uname) = 'Darwin' ]; then
            if [ -z $(which brew) ]; then
                ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
            fi
            brew install keychain
        elif [ $(uname) = 'Linux' ]; then
            git clone https://github.com/funtoo/keychain.git ${HOME}/keychain
            echo '\n\n## add keychain to path\nexport PATH="${HOME}/keychain:${PATH}"'
        fi
    fi
    echo -e '\n\n## start keychain\neval `keychain --agents ssh --eval '${privkey}'`\n\n' >> ${HOME}/.bash_profile
}
# Define Function
## Setup and add private key to agent
function stdssh_addagent(){
	local privkey=${1}
    if [ -z ${keychain} ]; then
        eval `ssh-agent -s`
        # Mac OS X specific params
        if [[ $(uname) = 'Darwin' ]]; then
            if [[ $(uname -r) = '16.5.'* ]]; then # make config file for Sierra
                echo -e "\nHost *\n  AddKeysToAgent yes\n  UseKeychain yes\n  IdentityFile ${ssh_home}/${privkey}\n" >> ${ssh_home}/config
            fi
        fi
        # Add private key
        ssh-add -K ${ssh_home}/${privkey}
        # Start SSH-AGENT at log in and log out
        echo -e '\n## start ssh agent at login\n[ -z "$SSH_AUTH_SOCK" ] && eval `ssh-agent -s` && ssh-add '${ssh_home}'/'${privkey}'\n\n' >> ${HOME}/.bash_profile
        echo -e '\n## quit ssh-agent at logout\n[ -n "$SSH_AUTH_SOCK" ] && eval `ssh-agent -k`\n\n' >> ${HOME}/.bash_logout 
    else
        stdssh_addkeychain
    fi
}
# Define Function
## Reset
function stdssh_reset(){
    ## Reset?
    if [ ${resetkeys} ]; then
        echo -e '\n'
        read -p "Are you sure you want to delete all ssh-agent files, .bash_logout and .ssh directory?  [Y/N]  :: " doublecheck
        if [ "${doublecheck}" = 'Y' ] || [ "${doublecheck}" = 'y' ]; then
            echo -e "\n\n 🔥🗑  Removing All Local Keys, Authorized Hosts & ssh-agent Settings"
            rm -v ${ssh_home}/${privkey}
            rm -v ${ssh_home}/${pubkey}
            rm -v ${ssh_home}/config
            rm -v ${sshagentfile}
            rm -v ${HOME}/.bash_logout
            #echo -e "\n\n 📡 ⚡️ ⚡️  Removing All Remote Keys, Authorized Hosts & ssh-agent Settings"
            #ssh ${user_alias}@${host} "rm -rv ~/.keys;"
        fi
    fi
}
# Define Function
## Run STDSSH for a 1-way handshake
function stdssh_run(){
    local host=${1}
    local user=${2}
    local key=${3}
    # Check for Reset
    stdssh_reset
    ## Run only if User confirms input arguments 
    confirm_input
    ## Check for Generate Keys Flag
    [ ! -z ${genkeys} ] && stdssh_genaddkeys
    ## Check for Copy Keys Flag
    [ ! -z ${cpkeys} ] && stdssh_cpkey ${host} ${user} ${key}
    ## Check for Add SSH Agent Flag
    [ ! -z ${addagent} ] && stdssh_addagent ${key}
    ## Run Entire Pipeline (Default)
    [ ! -z ${exec_all} ] && stdssh_genaddkeys && stdssh_cpkey ${host} ${user} ${key} && stdssh_addagent ${key}
    ## Set Appropriate Permissions
    stdssh_perms
}

# Run STDSSH
stdssh_run $host $user_alias $privkey

#####################################
### Shady El Damaty ; 24 April 2017
###
### stdssh / setup-sshkeys
#####################################